apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iicpc-bot-fleet-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iicpc-bot-fleet
  minReplicas: 10
  maxReplicas: 200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75 # Scale up when average CPU load exceeds 75%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 # Scale up when memory exceeds 80%
